### ISSUE TITLE
How to efficiently process a batch of terms in one go for Tree Neural Networks

### ISSUE THREAD

**Issue by brando90** [princeton-vl/CoqGym#16]
I know that for vision one can process the entire batch in one go by having the batch be a dimension in the tensor. Is something like this possible for Tree like NN? I am worried that having to do a forward pass for each example for my TNN might slow things down, but perhaps there is no other way. How do you do this, simply one term at a time?

(I assume multithreading might be possible but I don’t know how that would work with multiple threads/processing using the same gpu…plus debugging sounds like a nightmare. But I am curious what is the standard practice for this since TNN research exists.)

**Comment by yangky11** [comment]
Batching trees is possible but needs extra effort compared to images. 
Batching images is easy because all images have the same size (after preprocessing). You just have to stack them together to form a batch. 
For trees, however, you cannot simply stack them since they have different shapes. In this case, the implementation of batching often depends on each specific use case. For example, in [term_encoder.py](https://github.com/princeton-vl/CoqGym/blob/05fa4571b2d1e956bc791c4d742a09f550378af1/ASTactic/models/term_encoder.py#L152), I put nodes of the same height into a batch, and process them bottom-up. In other words, I first process nodes with height 0, then height 1, then height 2, etc.

**Comment by brando90** [comment]
discussion link: https://github.com/princeton-vl/CoqGym/discussions/48
