### ISSUE TITLE
Hidden states in TermEncoder accessed before initialized

### ISSUE THREAD

**Issue by vrjmath** [princeton-vl/CoqGym#17]
In the [TermEncoder](https://github.com/princeton-vl/CoqGym/blob/master/ASTactic/models/term_encoder.py) class, the hidden_states dictionary is declared at line 148 
` hidden_states = {} # node -> hidden state`, 
accessed at line 168 
`h = hidden_states[c]`, 
and initialized at line 185 
`hidden_states[node] = hiddens[i]`. 
I seem to be getting at error because hidden_states is empty when the code tries to access it at line 168.

**Comment by yangky11** [comment]
Thanks for your interest in our work!

In each iteration, we access the nodes of a specific height. And we iterate from height 0 to 1, 2, ... etc.
https://github.com/princeton-vl/CoqGym/blob/05fa4571b2d1e956bc791c4d742a09f550378af1/ASTactic/models/term_encoder.py#L152

Nodes with height 0 are leaf nodes. They do not have children. So this inner loop will not be executed in the first iteration of the outer loop:
https://github.com/princeton-vl/CoqGym/blob/05fa4571b2d1e956bc791c4d742a09f550378af1/ASTactic/models/term_encoder.py#L16

Therefore, `hidden_states` should have been initialized when it is accessed. For each node, we always access the hidden_states of its children, which are already initialized because we go from bottom to up.

Feel free to let me know if you have further questions.

**Comment by vrjmath** [comment]
Perfect, thanks!
