### ISSUE TITLE
CoqExn Error when starting next proof

### ISSUE THREAD

**Issue by zhaoyu-li** [princeton-vl/CoqGym#37]
Hi, kaiyu, I reinstall CoqGym on a new machine but when I run CoqGym, there is a new problem when starting some new proofs:

Traceback (most recent call last):
  File "evaluate.py", line 89, in <module>
    results.extend(agent.evaluate(f, opts.proof))
  File "/home/lizhaoyu/CoqGym/ASTactic/agent.py", line 173, in evaluate
    for proof_env in file_env:  # start a proof
  File "/home/lizhaoyu/CoqGym/eval_env.py", line 187, in __next__
    self.serapi.execute(cmd)
  File "/home/lizhaoyu/CoqGym/serapi.py", line 343, in execute
    state_id, ast = self.send_add(cmd, return_ast)
  File "/home/lizhaoyu/CoqGym/serapi.py", line 151, in send_add
    responses, raw_responses = self.send('(Add () "%s")' % escape(cmd))
  File "/home/lizhaoyu/CoqGym/serapi.py", line 134, in send
    raise CoqExn(sexpdata.dumps(parsed_item[2][4]), sexpdata.dumps(parsed_item[2]))
serapi.CoqExn: (CErrors\.UserError ("" "Compiled library Logic.lib.RelationPairs_ext (in file /home/lizhaoyu/CoqGym/coq_projects/UnifySL/lib/RelationPairs_ext.vo) makes inconsistent assumptions over library Coq.Structures.GenericMinMax"))

Specifically, maybe you can run `python evaluate.py ours astactic_CoqGym --path runs/demo/checkpoints/model.pth --file ../data/UnifySL/GeneralLogic/KripkeModel.json` to see this problem. Can you please help me figure this out?

**Comment by yangky11** [comment]
The error `XXX makes inconsistent assumptions over library YYY` happens when Coq is trying to use a file that is compiled using another Coq installation. I encountered this error a few times and they were usually because I happened to use the wrong Coq installation (e.g., the version installed by OPAM) for compiling some Coq projects. 

To fix the problem, you could remove CoqGym and all other Coq-related stuff on the new machine. Then install CoqGym from scratch. You should also double-check whether you are using the correct Coq (the locally compiled version in this repo) before this step:

> 5. Build the Coq projects (can take a while): cd coq_projects && make && cd ..

Feel free to ask if it still doesn't work.

**Comment by zhaoyu-li** [comment]
Ok, thanks!
