### ISSUE TITLE
extract_steps doesn't work if you change location of the data

### ISSUE THREAD

**Issue by brando90** [princeton-vl/CoqGym#42]
Hi Kaiyu,

I (eventually) saw:

https://github.com/princeton-vl/CoqGym/blob/97f109880fc85b2f4a8a76cea43388ae1b95f466/ASTactic/extract_proof_steps.py#L79

which doesn't allow users to have their own path to the data (e.g. some hpc services require us to have them in specific locations etc.)

For my particular path this worked:

```
    proj = filename.split(os.path.sep)[6]
```

but we might need to think of a different way of processing the data.

(Also, that file has global variables were values are being set outside and then passing the function with a specific value set outside. That type of thing makes it really hard to debug, perhaps using classes would be better? I'm a big fan of functional programming and having arguments be explicit to make it easier for others to edit and build on your code. Anyway, just trying to help )

**Comment by brando90** [comment]
another solution could be to host the data in some university box/drop box link that doesn't die (since universities usually pay for box or drop box).

**Comment by brando90** [comment]
also why aren't we extracting the test data?

```
    for split in ['train', 'valid']:
```

**Comment by yangky11** [comment]
1. For the path problem: I think requiring a specific path won't be problematic since one could always use symbolic links even if the data is stored somewhere else. But I agree it would be great to have a more flexible way of handling paths in the code.

2. For the global variable, feel free to submit a pull request.

3. For ` for split in ['train', 'valid']`: Our model is trained to predict individual proof steps. That's why we extract proof steps for training and validation. For testing, however, the goal for the model is to generate a correct proof rather than predicting a single proof step. See [eval_env.py](https://github.com/princeton-vl/CoqGym/blob/master/eval_env.py) and [agent.py](https://github.com/princeton-vl/CoqGym/blob/master/ASTactic/agent.py) for details.
